AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Books API

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Ref BooksTable

Resources:
  GetAllBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./get-all-books/
      Handler: main
      Events:
        GetAllBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
  
  InsertBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./insert-book/
      Handler: main
      Events:
        InsertBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: books
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
        - AttributeName: author
          AttributeType: S
      KeySchema:
        - AttributeName: title
          KeyType: HASH
        - AttributeName: author
          KeyType: RANGE


Outputs:
  GetAllBooksFunction:
    Description: "API Gateway endpoint URL for Prod stage for Books API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
    Export:
      Name: BooksApi
  BooksTable:
    Description: "Books DynamoDB table name"
    Value: !Ref BooksTable
    Export:
      Name: BooksTable
