AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Books API

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    Environment:
      Variables:
        BOOKS_TABLE: !Ref BooksTable

Resources:
  GetAllBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-all-books/
      Handler: books-api
      Events:
        GetAllBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: books
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
        - AttributeName: author
          AttributeType: S
        - AttributeName: isbn
          AttributeType: S
        - AttributeName: year
          AttributeType: N
        - AttributeName: description
          AttributeType: S
      KeySchema:
        - AttributeName: title
          KeyType: HASH
        - AttributeName: author
          KeyType: RANGE