on:
  workflow_dispatch:
    
# workflow to remove SAM stack on demand

jobs:
  clean_up:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - run: sam delete --stack-name books --no-prompts --region ${{ vars.AWS_REGION }}